In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from unicodedata import normalize

In [28]:
lang_map = {
    'eng_Latn': 'English', 'ind_Latn': 'Indonesian', 'sun_Latn': 'Sundanese', 
    'jav_Latn': 'Javanese', 'bug_Latn': 'Buginese', 'ace_Latn': 'Acehnese', 
    'bjn_Latn': 'Banjar', 'ban_Latn': 'Balinese', 'min_Latn': 'Minangkabau'
}

In [30]:
df = pd.read_html('https://meta.wikimedia.org/wiki/List_of_Wikipedias')[0]
df.columns = [
    'no', 'lang', 'lang_local', 'wiki_code', 'articles', 'all_pages', 
    'edits', 'admins', 'users', 'active_users', 'files', 'depth'
]
df = df.set_index('no')

In [31]:
df[df['lang'].isin(lang_map.values())]

,lang,lang_local,wiki_code,articles,all_pages,edits,admins,users,active_users,files,depth
no,,,,,,,,,,,
1,English,English,en,6652311,58113068,1148575852,905,45495362,126872,902512,1182
22,Indonesian,Bahasa Indonesia,id,645563,3501340,23369641,44,1403173,3019,47496,130
49,Minangkabau,Minangkabau,min,226661,387631,2505628,5,17451,44,178,3
84,Javanese,Jawa,jv,72474,181858,1630129,5,57280,70,5452,20
92,Sundanese,Sunda,su,61465,97847,654215,6,29743,53,545,2
126,Balinese,Basa Bali,ban,18802,37115,152330,4,7016,31,116,3
135,Buginese,ᨅᨔ ᨕᨘᨁᨗ,bug,15823,20090,202068,1,12882,14,0,0
166,Banjar,Banjar,bjn,10280,29208,87470,3,13523,28,2,10

In [5]:
df[1]

,Totals,Articles,All pages,Edits,Admins,Users,Active users,Files
0,All active Wikipedias,61046570,252237293,3335633908,3614,107695916,306426,2765344